### PR TITLE
Passing an executor to the `BoosterCatalogService.Builder`

### PR DESCRIPTION
**Pull request by quintesse**

### CODE REVIEW

**Comment by quintesse** [comment]
I'm using the `JoinFork.commonPool()` if no `executor()` gets passed, so I'm not sure if this change is even necessary. But it seemed like the proper thing to do.

**Comment by gastaldi** [comment]
You forgot to update the booster-catalog-service dependency to the next version

**Comment by quintesse** [comment]
Thought you preferred that as something separate given the fact the service isn't released on Maven yet. But I added it now. (But the -SNAPSHOT version)

**Comment by gastaldi** [comment]
Right, you can remove the SNAPSHOT and then we can merge this PR when https://github.com/openshiftio/booster-catalog-service/pull/8 is merged and released

**Comment by gastaldi** [comment]
Merged in https://github.com/openshiftio/launchpad-addon/commit/9b3b9e6dff67ec36beb260c35c05b3e4469d3bd0

**Pull request closed without merging**
