### PR TITLE
expose the inputs for maven coordinates to derived classes

### PR DESCRIPTION
**Pull request by jstrachan**
so that we can default the artifactId to the project name in fabric8/OSIO

### CODE REVIEW

**Comment by gastaldi** [comment]
Thanks!

**Comment by jstrachan** [comment]
wow that was fast! :)

**Comment by gastaldi** [comment]
Continuous Delivery at its best ;)

**Comment by jstrachan** [comment]
we just need automatic releases on merge to master ;)

**Comment by jstrachan** [comment]
(with automating PRs being generated on fabric8-generator as part of the CD pipeline! :)

**Comment by gastaldi** [comment]
That would be nice, and change the dependency version in the projects that depend on it

**Comment by jstrachan** [comment]
yeah! we do that on most fabric8 projects - its super handy. e.g. every fabric8-generator release does PRs on dependent projects (e.g. the runtime) https://github.com/fabric8io/fabric8-generator/blob/master/release.groovy#L43-L49 but we can do as many PRs as required. Then they show up like this:
https://github.com/fabric8io/generator-backend/commit/f08d8a7cfea57d0f57577069bdb362c3b2ee754e
which then triggers the CI jobs in downstream projects etc.

We should get the RHOAR stuff setup using fabric8/OSIO for CI / CD really!

**Comment by gastaldi** [comment]
This is awesome. I´ll have a look at it after the F2F week

**Comment by jstrachan** [comment]
right now we manually wire up downstream dependencies in the pipelines; but we'd rather do things a little more automatically and loosely coupled; by letting a project subscribe to version changes in its downstream dependencies; and to support other dependencies (e.g. spring / forge / whatever) that are released separately to your own local project
https://github.com/fabric8io/fabric8-platform/issues/156

**Comment by gastaldi** [comment]
Fantastic. You guys rock

**Comment by gastaldi** [comment]
It would be nice if we could enable this through a Github App, with a nice UI instead of adding specific release scripts to the codebase, my 2 cents ;)

**Comment by jstrachan** [comment]
agreed!

**Comment by gastaldi** [comment]
Can I bother you to help me enable this after Sept 25th? If you could point me to the docs I'd appreciate

**Comment by jstrachan** [comment]
sure! its just a matter of adding a suitable `Jenkinsfile` to any repos you want CI and/or CD for and adding your github organisations to our CI / CD infrastructure (which is fabric8 running on the public cloud): https://jenkins.cd.test.fabric8.io/. Ping me when you're ready and we can start moving some projects over to CI + CD via fabric8.

Its also really handy for UI stuff and system testing. e.g. on the CI side each PR can generate a separate docker image for testing before its merged to master (see any comment from @fabric8cd):
https://github.com/fabric8io/exposecontroller/pull/79#issuecomment-329621221

then for UI stuff we even deploy the new PR pointing at production back ends so you can test out the PR yourself before approving a PR: https://github.com/fabric8-ui/fabric8-ui/pull/1978 (though we tear down the UI once the PR gets merged so those links on the @fabric8cd comments on that PR won't be clickable any more)

**Comment by jstrachan** [comment]
BTW we're hopefully moving our CI / CD infrastructure over to be https://openshift.io/ ASAP (we're just waiting for docker builds to be enabled)

**Pull request merged**
